### ISSUE TITLE
生産性を高める社内ツールの選定

### ISSUE THREAD

**Issue by hirokiyamada-reno** [reno-shelter/test_repo#1]
# WHY

・社内の生産性が非常に悪いと感じた
・社内ツールが創業当初からほとんど変化がなく、じっくりと考えたことがなかった

以前、wantedlyの勉強会に行った際に、生産性の高さに驚いた。全員が仕事に集中して、全ての仕事を最速で終わらし、最速で改善を試みている様子を見たときに、このままでは勝てないと感じる。そのため、新年を機に社内の生産性を改めて考え、今年一年で圧倒的な生産性の向上を図っていく。

# WHAT

・社内の生産性を高めるための文化を明文化し、社内に浸透させる
・社内の生産性を高めるツールを選定し、運用ルールを設定する

# アウトプット

・生産性を高めるための社内文化の明文化
・社内ツールの選定
・運用ルールの明文化
・導入方法の決定
・導入スケジュールの設定

**Comment by ryotakodaira** [comment]
確認完了

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

まず、生産性が低いと感じる現在の事象を洗い出したい

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

LINEで業務連絡が流れてしまい情報の認識に抜けがある
議論の内容がほとんど文章化されていないため議論に参加していなかったメンバーへの内容共有が満足にされていないか共有が二度手間になる

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

そうだね。大きく分けると４つかな？

・情報共有が下手
・ミーティング・議論が下手
・タスクが明確じゃない
・オフィスで集中できない

言ってくれたのは、情報共有と議論についてだね。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

はい、こんな感じですね

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 
おけ。そうすると、

・全員が全ての情報を共有できていること
・ミーティングは最小限に抑えること
・タスクが明確で、全員が次にやるべきことをわかっていること
・全員が仕事に集中できること

これが実現されていると生産性は上がるって感じでいい？？

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
後、誰がどのタスクを抱えているのかが把握出来ていること。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 
おけ。

・全員が全ての情報を共有できていること
・ミーティングは最小限に抑えること
・タスクが明確で、全員が次にやるべきことをわかっていること
・誰がどのタスクを抱えているのかが常に把握出来ていること
・全員が仕事に集中できること

これを実現していこう。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

上記を実現する上で、組織として、こういう考え方、文化が当たり前になっていたほうがいいなってことはある？いくつでもいいので。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

・基本的な会話はツール上で行い、会話内容を全員が把握できるようにする。
・その日にやること、やったことを報告する。
・ミーティングには事前に考える期間を与える。
・個別のミーティングで決定した事項に対しては全て全員に報告する。
・議論したい事項に対して今すぐ議論を行うべきかを考える。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

・決定事項を全て文章化する。
・

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

かなり細かくていいね！！
これを文化として、そして仕組みとして定着させたいね。

文化としてはどう明文化していこうか？

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

・基本的な会話はツール上で行い、会話内容を全員が把握できるようにする。→ツールの指定
・その日にやること、やったことを報告する。→日報
・ミーティングには事前に考える期間を与える。→ミーティングを行う上でのルール
・個別のミーティングで決定した事項に対しては全て全員に報告する。→議事録
・議論したい事項に対して今すぐ議論を行うべきかを考える。→issue
・決定事項を全て文章化する。→議事録

で、仕組みとしては成立するね。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

ツールの使い方のドキュメントの中に文化として定着させたいことを含めるのはどうですか？

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

文化に関しては、常に見る、感じるようにしなきゃだねー。

>ツールの使い方のドキュメントの中に文化として定着させたいことを含めるのはどうですか？

も、有効だね！！

文化の明文化は何か表現思いつく？

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

実際に文化として定着させたい行動の見本を画像＋文章で表現する。
全ての文化を一つのキーノートファイルにまとめる。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

その文化を表す文章って何かある？

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

こういうのって、何でまとめるのがいいんだろうね？
いつもKeynoteで作るけど、実際誰も見ないよねww

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

まずはwikiがいいかなー？

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

何かクラウドなどで共有していつでもどこからでも開けるようにはした方がいいと思います

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
キーノートよりはwikiの方がいいのではないかな

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

じゃあ、まずはwikiに書こう。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

wikiってgithubのwiki機能使います？

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

>wikiってgithubのwiki機能使います？

そうだね。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

了解です。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 
文化に関して、明文化するとこんな感じかなと思うのだが、どう？？

１、エンジニアスタンダード
1-1、徹底的に楽をしろ
1-2、仕事のペースは自分で決める
1-3、信じるのは人ではなくデータ

2、ラーニングアニマル
2-1、最大の関心、最小の支援
2-2、長期の利益、短期の損失
2-3、無駄こそ限界突破への道

3、「ゾーン」is king
3-1、ゾーンの邪魔こそ最大の罪
3-2、ミーティングは時間の無駄使い
3-3、情報は吐き出し続けろ

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno
 
エンジニアスタンダードに
聞かない(質問しない)は罪
を追加したいです。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

エンジニアスタンダードの中で、削れるものある？
それぞれ3つはバランス良いよね

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
そうすると、以下ですかね。
>1-2、仕事のペースは自分で決める

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

おけ。そしたらそれを置き換えて

１、エンジニアスタンダード
1-1、徹底的に楽をしろ
1-2、聞かない(質問しない)は罪
1-3、信じるのは人ではなくデータ

にしよう。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
はい、それでいきましょう！

**Comment by hirokiyamada-reno** [comment]
上記の生産性を高める文化を推し進める上で、以下のツールは問題があると。それは以下のような問題であってる？他の問題や、他のツールで問題がある場合は挙げてほしい。

LINE,Facebookメッセンジャー
・話題が流れてしまう
・１つのテーマしか話せない
・ファイルの保存期間が短い
・セキュリティーに問題あり
・公私が混同する

thunderbird
・アーカイブが残らない
・検索が弱い
・ローカルにしか保存できない

trello
・放置されやすい
・期限がわかりにくい
・通知が多すぎる

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
>他の問題や、他のツールで問題がある場合は挙げてほしい。

googledrive
・公開範囲がわかりにくい
・流出させてはならいないファイルに簡単にアクセス出来てしまう。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

>googledrive
・公開範囲がわかりにくい
・流出させてはならいないファイルに簡単にアクセス出来てしまう。

その通りだね。これらは最低限解消していきたいね。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

で、俺がお正月で選定したのが、以下。それぞれ、ここ数日で使ってみてコメント欲しい。

・メール
-Gmail

・チャット
-slack

・社内SNS
-yammer

・バージョン管理
-github

・ファイル共有
-google drive

・スケジュール
-google カレンダー

・タスク管理
-todoist for business

・ナレッジ管理
-inc

・webhock
-zapier

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

こちらでも、
・選定理由
・メリット
・使い方

などをまとめておくので。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
了解です！

googleのツールについてはGoogle Apps for Businessは使わない予定ですか？

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

よろしく！！

>googleのツールについてはGoogle Apps for Businessは使わない予定ですか？

あー。そんなんあったね！！ちょっと調べる！！良さそうだったら、候補に入れるわ！！

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

そんな感じで、今日は以上で。また、明日か、明後日に。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

了解です。
お疲れ様でした。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
社内SNSでYammerを使う理由ってありますか？
slackでも同様の機能を持たせることができると思うのですが。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

そこに関しては、一番の悩みどころなんだよね。ただ、slackのみですべてをやろうとすると、slackの良い点（ゆるくて、情報を出すやすい）がなくなってしまう可能性があるかなとも思ってる。なので、今のところの想定は次のような使い分け。
![001](https://cloud.githubusercontent.com/assets/16508238/12110822/4ceaf21c-b3d3-11e5-9fa6-0cfd31981941.jpeg)
![004](https://cloud.githubusercontent.com/assets/16508238/12110824/531d2d26-b3d3-11e5-823c-f9aa7ec7c599.jpeg)
![005](https://cloud.githubusercontent.com/assets/16508238/12110825/55957996-b3d3-11e5-8d36-86308cba0bba.jpeg)

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
質問の部分でgithubとslackの使い分けの線引きが曖昧な気がします。
だんだんめんどくさくなってslackで質問するようになりそう。

質問の分類を単純に質問の内容を全員が見たほうがいいかで分けたほうが使う時にわかりやすいと思います。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

そうだね。複雑化を避けるために、yammerでの質問はなしにして、
個人の質問→slack
全員が見るべき質問→githubかな？

もしくは
業務に対する質問→slack
事業に関する質問→githubか

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

>個人の質問→slack
>全員が見るべき質問→github

これが使い分けとしては一番分かりやすく定着しやすいと思います。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira  @kokihori 

オッケー。そしたら、コミュニケーションに関しては以下の４ツールかつ使い方でいいかな？

![001](https://cloud.githubusercontent.com/assets/16508238/12229365/562174f8-b88a-11e5-87ab-26c7d93b84b8.jpeg)
![004](https://cloud.githubusercontent.com/assets/16508238/12229370/5c2a4aa0-b88a-11e5-8082-5d79cb48468f.jpeg)
![005](https://cloud.githubusercontent.com/assets/16508238/12229375/61146fb4-b88a-11e5-9d45-86ff674c9986.jpeg)
![006](https://cloud.githubusercontent.com/assets/16508238/12229379/661648e8-b88a-11e5-81ac-dbb216e692df.jpeg)

**Comment by kokihori** [comment]
@hirokiyamada-reno 
いいと思います！運用開始当初からそれぞれの線引きをしっかりすることが大切ですね。
しっかりと徹底していきましょう。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
いいと思います。
これなら運用のイメージが以前よりも出来ます！

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira  @kokihori 

ここまでで、少し課題感を感じていたことを解決できそうなものを考えたので、意見が欲しい。

### 課題
* incの連携が悪い（せっかくのストック情報が見られない可能性が高くなる）
* yammerでできる機能の多さの割りに、使う範囲が狭い（本当にyammerを使う必要があるの？という疑問が湧く）
* 分報と日報の関係性を考えると、全てslack上で完結させたくて、それならyammerは有効（むしろこれがyammerを使う一番の理由になる可能性が高い。＊yammerならzapierを使うことで日報を自動的にyammerに投稿することが可能。）

つまり、フローの情報とストックの情報、そしてその中間の日報（まずは導入したい）という三つの情報を適切に管理したい時に、それぞれ別のサービスを使う必要がある。

フロー→slack
ストック→github wiki,inc
日報→yammer

これをもう少しすっきりまとめられないかという意見はもっともだと思い、小平氏的には[quita team](https://teams.qiita.com/)がありなんじゃないかという話。

これについて、考えていてもう一つ候補としてあげたいのが、[esa.io](https://esa.io/)

両者の違いは以下を参照
http://www.lanches.co.jp/blog/3242
http://blog.mmmcorp.co.jp/blog/2015/09/19/qiita_vs_esa/

いろいろ読んでみて、もしかしたらesa.ioのほうがいいかもと思う。
quita teamよりも良い点は
* 値段
* 非エンジニアのとっつきやすさ
* 情報の分類が適切にできる（ストックの役割を完璧に果たせる）

あたり。特に分類は非常に重要かなと。これができることで、日報とストックの両者の情報管理を一つのサービスでできる気がする。

あとは、slackで日報を書く→esaもしくはquita teamに自動投稿ができないかなと思ったのだが、[これ](https://www.npmjs.com/package/nippo)で、できる感じがする。

なのでesaもしくはquita teamの導入で
フロー→slack
ストック→esaもしくはquita team
日報→slackからesa

にまとまるので、良いのではと思っているのだが、どう思う？？

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

記事読みました。

情報の分類、コストというところで考えるとesaの方がいいかなと思いました。
ただ、非エンジニアのとっつきやすさはどっちも変わらないなと感じます。
qiitateamは情報の分類がディレクトリ構造じゃない分タグで管理できるから検索も不自由なくできます。
エンジニアが中心なって使うことを考えるとqiitateamのがいいですね。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

この二つは微妙に設計思想が違うから、その微妙な違いが、今後大きな差になっていくとは思うよねー。非常に難しい選択だなー。どちらも、無料で使える期間があるから、両方とも使ってみて、判断するのが正しいかな？？

エンジニアが絶対にquita teamのほうが良いのなら、エンジニアスタンダード的にquita teamを採用するけど。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

どっちも使ってみたいってのはありますね。
qiita:teamに期待している機能があるのかを確かめたいので来週使ってみます。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira  @kokihori 

両方使えたら、感想の共有をお願い。

**Comment by kokihori** [comment]
@hirokiyamada-reno @ryotakodaira 
カレンダーの共有って最適化できないですかね？
新しい人の追加をいちいちするのが大変なので、グループに入ったら自動的に同じグループに入っている人も見られるように出来ないかな？

**Comment by hirokiyamada-reno** [comment]
@kokihori 

カレンダーの最適解は今のところ、有料版googleだろうね。
一人当たり月500円払う価値をどう考えるか。
そんな遠くないタイミングで有料版にするのは間違いないのだが、タイミングだけだね。

**Comment by kokihori** [comment]
有料版か…
見てみたらメンバーの出入りが激しい場合はフレキシブルプランの方が良さそうですね。これだと一人あたり６００円だけど。
でも有料版にする前に他のサービスに慣れる方が重要だし、やはりタイミングですね。

**Comment by hirokiyamada-reno** [comment]
@kokihori 

有料版だったら、ミーティングルームの予約管理とかもgoogleカレンダーで、できるから、最初の想定ではオフィス移転のタイミングでやろうかなとは思っていた。正直オフィス移転がこんな早くなるとは思ってなかったけどww

なので、最短だと3月から導入するって手はあるかなと今は思っている。
