### ISSUE TITLE
社内ツールの最も最適な連携の仕方について

### ISSUE THREAD

**Issue by hirokiyamada-reno** [reno-shelter/test_repo#2]
# WHY
社内ツールは出揃ったが、連携がまだ決まってない
連携を最適化することでパフォーマンスを最大化できるので

# WHAT
社内ツールのどれとどれを何のタイミングでどのように連携させるのか

# アウトプット
連携させるものとその内容の一覧化

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
これは明日まとますね。
基本、zapierを使った連携を考えれば良いですか？

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

そうだね。slackとかは純正で連携可能だから、どう使い分けるかどかだね。
今、堀ちゃんとzapierをいろいろ試してる。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

slackってどうやって始めればよいですか？
招待とかがあったらお願いします。
ryota.kodaira@reno-works.com

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 
今、招待した

**Comment by hirokiyamada-reno** [comment]
あああああ

**Comment by hirokiyamada-reno** [comment]
今日連携したもの

・github→slack(issue,commit,pull requestが実行されたら#githubに通知)
・todoist→slack(新しいタスクが追加されたら#事業部ごとのチャネルに通知)
・slack→yammer(【日報】という文字が含まれたらその内容を投稿)

上記は良い感じだった。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

>github→slack(issue,commit,pull requestが実行されたら#githubに通知)
・pushやpullは通知出来ませんか？
・commitのコメントもslackで見れます？

inc →　slack(incに投稿があったら通知)

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

> ・pushやpullは通知出来ませんか？
slack純正の連携ではできないねー。zapierならできるかも。

> commitのコメントもslackで見れます？
なんでもいいから、コミットしてみてー。

incがzapier使ってもできそうにないんだよねー。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira @kokihori 
現状まとめます。

・github→slack(issue,commit,pull requestが実行されたら#githubに通知)
・todoist→slack(新しいタスクが追加されたら#事業部ごとのチャネルに通知)
・slack→yammer(【日報】という文字が含まれたらその内容を投稿)

以上はできることが確認されており、実装方法もわかっています。
その他で、必要そうな連携はありますか？

**Comment by kokihori** [comment]
@hirokiyamada-reno @ryotakodaira 

![inc_integrations](https://cloud.githubusercontent.com/assets/16537278/12149627/10e74ab6-b4e8-11e5-832d-f1c2b1bd73f4.jpg)
incのページには連携サービス書いてますが、incから他サービスに共有できるのはflowdockとhipchatだけみたいですね。他の４つのサービスは基本的にincに向けて転送できる連携と書いています。

incデザインとかはいいけど他のサービスとの勝手が悪いですね…

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno @kokihori 

googleドライブに議事録をアップした時などドライブにファイルがアップされたらslackに通知が行く。
これが出来たら良いかと。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira @kokihori 

> googleドライブに議事録をアップした時などドライブにファイルがアップされたらslackに通知が行く。これが出来たら良いかと。

それは、できそうだね。
あとは議事録の管理方法をどうするかだな。ドライブ管理にするのか、github管理にするのか。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno @kokihori

>あとは議事録の管理方法をどうするかだな。ドライブ管理にするのか、github管理にするのか。

githubの場合の管理方法はwordファイルをリポジトリにpushするって感じになりますよね。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira @kokihori 

wordファイルと.mdだとwordファイルのほうがいいかな？

**Comment by kokihori** [comment]
@hirokiyamada-reno @ryotakodaira 
githubの中だと他のディスカッションで埋もれてしまう気が…
連携のしやすさの観点からもdriveにwordファイルでアップするのが一番わかりやすい気がします。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno @kokihori

もしgithubにするなら.mdの方がいいと思います。
wordだとgithub上で中身を確認できないので。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira @kokihori 

github
メリット
* 作成コストが低い
* マークダウンで書き方を統一できる
* issueと同じ空間で見れる

デメリット
* 埋もれる可能性がある
* どこにあるかがわかりづらくなる可能性がある

drive
メリット
* 慣れている
* 管理が容易
* 保存場所が明確

デメリット
* わざわざドライブに行かないといけない
* ただの保管場所となり、読まれない可能性がある
* wordのため作成コストが高い

今のところこんな感じかな。一度、mdファイルでやったらどうなるか見てみたい感じもするかな。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
今、サンプルで議事録アップしてみました。
github管理のデメリットとしてはmdファイルで自分で作ってプッシュするのがめんどくさいところですね。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 
githubのリポジトリって階層構造って作れるよね？

wordファイルで作るよりもmdファイル作るほうが時間かかる？

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
>githubのリポジトリって階層構造って作れるよね？

階層構造作れますよ。フォルダ作ってその中にアップするだけです。

>wordファイルで作るよりもmdファイル作るほうが時間かかる？

いえ、作成時間はワードとほぼ同じかワードよりもかからないと思います。
作成時間に関してはmdの慣れかと。
pushらへんの仕組みをしっかり説明してあげれば大丈夫。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

なるほど。エンジニアとしてはどっちのほうがいい？

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

エンジニアとしてはgithubで管理ですねー。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira @kokihori 
> エンジニアとしてはgithubで管理ですねー。

それならば、まずはgithubでいきたいね。
エンジニアにとっての日常のコストが一番低いことを最優先したいので。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira  @kokihori 

その他必要そうな連携はなさそう？
ないなら、closeするけど。

**Comment by kokihori** [comment]
@hirokiyamada-reno 
結局incの連携はなしですか？
僕はリンクの共有専用のslackチャンネルを作ってもいいと思う。

**Comment by hirokiyamada-reno** [comment]
@kokihori 

incは連携できないんじゃなかったっけ？
何か方法あるなら、連携したいね。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

今のところ僕からはこれ以上無いです。

**Comment by hirokiyamada-reno** [comment]
### 結論

・github→slack(issue,commit,pull requestが実行されたら#githubに通知)
・todoist→slack(新しいタスクが追加されたら#事業部ごとのチャネルに通知)

議事録はgithubで管理
