### ISSUE TITLE
slackの初期設定におけるチャネルのブレスト

### ISSUE THREAD

**Issue by hirokiyamada-reno** [reno-shelter/test_repo#3]
# WHY
slackを効果的に運用したいため

# WHAT
slackのチャネルは何が必要でどう分けたら最適かを決める

# アウトプット
チャネルの一覧と目的及び用途

**Comment by hirokiyamada-reno** [comment]
・分報チャネル（個人ごとに）[参考リンク](http://c16e.com/1511101558/)
・事業別チャネル（事業ごと）
・雑談用
・github用

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira  @kokihori 
こちら、何かあったら追加よろしく。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

・プロジェクト全体(営業もエンジニアも参加)
・開発チーム(各プロジェクトのエンジニアのみ)ごと

**Comment by kokihori** [comment]
@ryotakodaira 
プロジェクト全体はgeneralじゃダメですかね？
開発チームごとのチャンネルは必須ですね。

**Comment by hirokiyamada-reno** [comment]
プロジェクトが複数（新卒紹介・新サービスなど）あるから、それごとの全体チャネルってことじゃない？

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno @kokihori 

>プロジェクトが複数（新卒紹介・新サービスなど）あるから、それごとの全体チャネルってことじゃない？

そうそう。山田くんの言っている通りです。
なので以下はあったほうが良いと思います。

>・プロジェクト全体(営業もエンジニアも参加)
>・開発チーム(各プロジェクトのエンジニアのみ)ごと

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

プロジェクト全体と事業別チャネルの違いって何かある？

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

あ、ごめんなさい。
プロジェクト＝事業部でいいのか。
そうしたら以下の分け方はどうです？
・プロジェクト全体チャネル(新卒紹介、ソーシャルヘッドハンター)
・社内の営業が全員いるチャネル
・社内のエンジニアが全員いるチャネル

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

> 
・プロジェクト全体チャネル(新卒紹介、ソーシャルヘッドハンター)
・社内の営業が全員いるチャネル
・社内のエンジニアが全員いるチャネル

うん。この分け方でいいかもね。

**Comment by hirokiyamada-reno** [comment]
@kikukawa-reno 
なんか欲しいのあったら書いてねー

**Comment by hirokiyamada-reno** [comment]
@kikukawa-reno 
もう一回

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira  @kokihori 

こちらはもう大丈夫そうかな？
明日の午前中までに何もコメントつかなかったら、クローズします。
