### ISSUE TITLE
githubのタグの種類

### ISSUE THREAD

**Issue by hirokiyamada-reno** [reno-shelter/test_repo#4]
# WHY
githubのissueにおける正しいタグの種類を作ることで、isuueを正しく振り分けたいため

# WHAT
githubのissueにつけるタグの種類を決める

# アウトプット
タグの一覧化と用途

**Comment by hirokiyamada-reno** [comment]
エンジニア
・バグ
・機能追加
・改善事項
・実現不可能
・わかっているが対応しない

ビジネスサイド
・改善要望
・重要
・全員参加

共通
・質問
・緊急
・改善事項
・重複

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

>エンジニア
>・バグ
>・機能追加
>・改善事項
>・実現不可能
>・わかっているが対応しない
・ドキュメント
・仕様や機能の議論

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira  @kokihori 

現時点で出てる分でも、かなり多くて迷いそうだから、必要、不要、統合をしていこうか。
何か、不要、統合できるものあったら、書いてー。

**Comment by kokihori** [comment]
@hirokiyamada-reno 
エンジニアのとこに書いてある
・実現不可能
・わかっているが対応しない
って要りますかね？

どういう時に使うのかが想像できない。

**Comment by kokihori** [comment]
あと、改善関係のタグは１つにまとめていい気がします。
改善の中で「要望」と「事項」でさらに分類されていると細かすぎる気が。

**Comment by hirokiyamada-reno** [comment]
@kokihori  @ryotakodaira 

> エンジニアのとこに書いてある
・実現不可能
・わかっているが対応しない
って要りますかね？

これはgithubの初期設定で入ってるんだよね。

りょうちん、エンジニアとしてはどう？

**Comment by hirokiyamada-reno** [comment]
要望・事項は全て要望でまとめようか。

**Comment by kokihori** [comment]
@hirokiyamada-reno 
共通の「重複」ってどういう時に使うものですか？

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno @kokihori 

>>エンジニアのとこに書いてある
>>・実現不可能
>>・わかっているが対応しない
>>って要りますかね？

>これはgithubの初期設定で入ってるんだよね。
>りょうちん、エンジニアとしてはどう？

これはどちらも必要。
このタグってissueを立てる時に付けてその後は一切変更しないってことは無いと思うんだよね。
issue内での議論の結果、タグが実現不可能やわかっているが対応しないに変更されることは十分にありえる。

**Comment by hirokiyamada-reno** [comment]
@kokihori 

重複は過去にissueとして立てて、回答だったり結論が出てる場合は、重複にして、前回のissueのリンクを貼って終わらすって感じかな

**Comment by kokihori** [comment]
@hirokiyamada-reno 
なるほど、了解です。
実際に使い始めたらまた必要なタグが出てくるとは思いますが、現時点ではこれでいいと思います。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira @kokihori 

では、結論として以下で一回運用するって形で良いかな？

エンジニア
・バグ
・機能追加
・実現不可能
・わかっているが対応しない

ビジネスサイド
・全員参加

共通
・質問
・緊急
・改善要望
・重複
・重要

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

上で1回発言していたのですが、
エンジニアに
・ドキュメント
・仕様や機能の議論
を追加します。
他に関してはよろしいと思います。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira @kokihori 

そうだ。

てことは、以下かな？

エンジニア
・バグ
・機能追加
・実現不可能
・わかっているが対応しない
・ドキュメント
・仕様や機能の議論

ビジネスサイド
・全員参加

共通
・質問
・緊急
・改善要望
・重複
・重要

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
はい、これでOKっす！
これで一旦クローズしますね。
