### ISSUE TITLE
現時点での最適なメールツール及び運用方法

### ISSUE THREAD

**Issue by hirokiyamada-reno** [reno-shelter/test_repo#6]
@ryotakodaira  @kokihori 

### WHY

今のサンダーバードは様々な問題点が発生している

* アーカイブが残らない
* 検索が弱い
* ローカルにしか保存できない

これらの点を解消したいため

### WAHT

現時点の規模において最適なメールツールの選定とその運用方法の決定

### アウトプット

使うメールツールと運用方法の資料

**Comment by hirokiyamada-reno** [comment]
### メールで実現したいことの一覧

* クラウドからメールを送れる
* クラウドにログが残り、検索することができる
* 複数のアドレスを併用して使うことが容易

**Comment by hirokiyamada-reno** [comment]
### 上記の実現したいことを実現できるツール

* クラウドからメールを送れる　→　gmailのみ
* クラウドにログが残り、検索することができる　→　google apps for work
* 複数のアドレスを併用して使うことが容易 →　gmailのみ

メールのログを確認するのをgmail上でやりたいならgoogle apps for workは必須だが、さくらサーバーからでいいならgmailのみで問題ない。gmailの設定を各々正しく設定出来る資料を作れば大丈夫。

**Comment by hirokiyamada-reno** [comment]
### ツール選定の結論

googleメールを用い、設定に関する資料を作成する

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

### 残りの課題

設定に関する資料の作成。こちらに関していつまでに、誰が作るのか。これを決めよう。正直、小平氏が作るほどのものでもない気はする。何か参考ページがあるなら、それを見ながら、俺が作っちゃってもいいかなと思うが、どうする？

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

そうですね。資料作りはお願いします。
参考資料は俺の方でも用意します。

後、サンダーバードで受信したメールが消える問題については原因が判明しましたが、
一旦、各々のメール設定をリセットした方が良いと思いますので、gmail導入前に全メールアドレスのパスワードを変更します。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

参考資料だけ用意お願い。用意され次第、すぐに作成に取り掛かるので。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

参考資料

初期設定
http://codecake.co.jp/blog/gmail-sakura/

ラベル設定
http://www.tabroid.jp/news/2014/05/gmail-label.html

通知設定
https://support.google.com/mail/answer/1075549?hl=ja
