### ISSUE TITLE
リンクの共有ツール代替案

### ISSUE THREAD

**Issue by kokihori** [reno-shelter/test_repo#7]
@ryotakodaira @hirokiyamada-reno 

# WHY
incを使ってのリンクの共有が効率的ではないため。

# WHAT
**簡単に**、**気軽に**、**素早く**リンクを社内で共有できる新たなツールの選定。

# リンク共有ツールに求める機能など
* マルチプラットフォーム→incでは不可
* 他サービスとの連携(slack)→incでは不可
* 投稿に対して直接のコメントが可能→incでは可

**Comment by kokihori** [comment]
incがあまりにも使えないので、他のサービスを検討したいです。もし他にいいサービス知っていたり、他のサービスを検討するときにあったらいいなと思う条件があれば教えてください！

**Comment by kokihori** [comment]
特にincでの致命的なのはアプリがないことだと思いました。
これいい！って思ったときにすぐにスマホからリンクが共有できないのは痛い。
共有したい！って思ったときにすぐに共有できるのはすごく大事だと思います。
実際にincを使っていて、アプリがないためにスマホを見ているときに後で共有しようと思って忘れてたor後では熱が冷めて共有しなかったことも多くありました。
これは特に解決したい。

**Comment by kokihori** [comment]
@ryotakodaira @hirokiyamada-reno 
pinterestとかどうですかね？
個人的にも使っていますが、なんでも放り込めるし便利ですよ。
リンクとかの共有だとページの画像とサイト概要が自動的につくので見やすいし。

**Comment by hirokiyamada-reno** [comment]
@kokihori  @ryotakodaira 

piterestの気になるとことは
・フローメインであり、ストックの要素が弱い気がする
・画像を扱うことがメインのサービスのため、それを記事化していくことに限界があるのでは
・個人で使うことがベースのため、組織でどこまで使えるか、又は私的なものと混ざり合うリスク

ここらへんかなー。

今試してる
quita teamとesa.ioはどう？
使った感触、incの役割を同時に果たせないかなど、感想、意見があれば聴きたい

**Comment by kokihori** [comment]
今日の話し合いで結論が出たのでクローズします！
