### ISSUE TITLE
留年した場合の対処法

### ISSUE THREAD

**Issue by ichiro-eita** [reno-shelter/test_repo#8]
### WHY

イチローが留年する可能性が20％程度あるため、その場合の対策を考えてリスクヘッジしておきたい。

### WHAT

仮に留年した場合、何をすればいいか

### アウトプット

留年した場合の行動計画

**Comment by ichiro-eita** [comment]
@ryotakodaira  @hirokiyamada-reno  @kokihori  @saki-ando  @taronkjm 

みなさん意見を下さい。

### イチローの意見

前期で単位を取り終えて、旅行（世界一周）へ行く。

**Comment by kokihori** [comment]
<h1>堀の意見</h1>
まず留年が確定した場合はすぐに内定先のimaに連絡をして、内定を１年後に持ち越せるのかを確認したほうが良いかと。
OKならば世界一周も可能ですが、NGなら旅は諦めて就職活動を行ったほうが良いと思います。


<h4>まあなるようになるだろうから今はあまり深く考えずに行きましょ！</h4>
