### ISSUE TITLE
17卒新卒紹介の営業資料構成案

### ISSUE THREAD

**Issue by hirokiyamada-reno** [reno-shelter/test_repo#9]
# WHY

そろそろ以前の資料が使えなくなって更新する必要があるため

# WHAT

新卒紹介の営業資料の構成案を確定させる

# アウトプット

営業資料の構成案

**Comment by hirokiyamada-reno** [comment]
@saki-ando  @kikukawa-reno  @ichiro-eita 

17卒の新卒紹介の営業資料の構成案を作成しました。
1/31までに意見や、質問、承認をください。承認が下り次第、ラフデザイン・本作成に移ります。

# 営業資料の目的・狙い

以下の優先順位で資料の目的を定めた

1. 資料送付でのアポ獲得を最大化する
1. 訪問時の説得力を高める
1. RENOのメインターゲットのみが反応するようにする（ターゲットから外れるお金にしにくい企業の増加を避けるため）
1. RENOのコンセプトを理解してもらい、過度な期待値の醸成を防ぐ
1. 申込後のやり取りをスムーズにする

# 読み手のストーリー

以下の読み手の感情の変化を目指したストーリラインを考えました。

| 順序 | 読む前の心理 | 読んだ後の心理 |
| --- | --- | --- |
| 1 | この会社はどんな会社なんだろう？ | なるほど。そんな考えで人材業界で会社を作ったのか。ちゃんとした会社っぽいな。 |
| 2 | ここの新卒紹介は他と違いがあるのだろうか？ | なるほど。ここは確かに他とは少し違そうだ。 | 
| 3 | この特徴を持った新卒紹介ってうちは使うべきか？ | 確かに、この課題を持ってるうちなら、ここの新卒紹介は使ったほうが良さそうだ。 |
| 4 | しかし、こいつらが言ってることは本当なのだろうか？ | 実績は出てるようだ。この辺の会社も使ってるのか。それは安心だな。 |
| 5 | そういえば、今年はどんな母集団が集まってるんだ？ | なるほど。すでにこれだけ集まって、今後も増えていくのか。|
| 6 | 使わない理由はなさそうだな。導入は簡単か？ | すぐに導入できそうだ。じゃあ、とりあえずお願いしとこうか。 |

# 構成案

ストーリーを想定した上で、具体的な構成案・載せる情報の案を作成しました。

| ページ数 | 大項目 | 記述内容 |
| --- | --- | --- |
| 1 | 会社概要 | 会社の基本情報・ミッション |
| 2 | 会社概要 | 代表紹介・株式紹介 | 
| 3 | サービスコンセプト | コンセプト・メンター説明 |
| 4 | 特徴 | マッチング率の高さ・値段の安さ |
| 5 | ターゲット | RENOが最も得意とする採用の課題一覧 |
| 6 | 実績 | 導入事例（16卒ミクシィ）|
| 7 | 実績 | 導入事例（16卒ベイカレントコンサルティング） |
| 8 | 実績 | 昨年の数値実績（母集団の総合計・総内定数・総辞退数・内定辞退率・総紹介数） |
| 9 | 母集団 | 現在の母集団の人数と今後の推移 |
| 10 | 母集団 | 現在の母集団の志望職種・業界 |
| 11 | 導入方法 | 申し込みから紹介までの流れ |
| 12 | 注意事項 | 導入にあたっての注意事項（提供してもらう情報・紹介の連絡方法） |

**Comment by ichiro-eita** [comment]
営業資料の母集団の構成に関して。
テレアポを行っていて、たまに人事の方が言うのは、体育会系の学生が多いとか趣向別に紹介会社を利用しているみたいなことを言ってくる。
そこに対しRENOの母集団の学生の趣向（部長経験など）のデータがあれば人事の方にもより母集団が想像しやすいのではないかと思った。山田さんから聞いた属性を上手く活用することで可能ではないかと自分は思いました。
みなさんの意見あれば宜しくお願いします。

**Comment by hirokiyamada-reno** [comment]
人事が言う、体育会系とかって言葉はかなり経験に焦点が当てられていて、正直それをデータ化するのは不可能なため、営業資料に載せることはできないという判断を行いました。なので、そこに関しては、口頭で伝えてもらうしかない。その代わり、その学生をタイプ別に分けている「属性」なら、ニュアンスくらいは伝えられるかなと。以下が属性の種類です。それを面談している中の経験・考え方・雰囲気で判断しています。

火→体育会系の熱くガツガツ行動していく雰囲気 
水→感情よりも論理を優先。コミュニケーションは必要な分だけ。行動するよりもまずは頭を使って考えたタイプ 
木→平和主義で落ち着いている。人が好きでどんな人とも上手くコミュニケーションを取ろうとするタイプ。熱すぎる人は少し苦手。 
光→何事も主張が強く、見た目が派手。誰もが憧れるようなライフスタイルを目指しそのための努力は惜しまない。仕事もプライベートも充実させたいタイプ。 
闇→コミュ障で、なるべく一人でいたい。扱い方が難しい。しかし、はまれば威力を発揮する

こちらを資料に入れるべきか。意見があればお願いします。

**Comment by kikukawa-reno** [comment]
うちのシステム上で一応管理している能力値や特性のデータは記載しておくといいと思います。
ユニークっていう部分と、マッチング率が高いって部分の裏付けの目に見える数値的データの根拠があると信頼性あがるかと思います。
そういった意味で、どんな学生がいるかっていうのを、定性的な言葉や文章で伝えるより、定量的に伝えた方がいいかと思います。
SFでそれぞれどれくらいいて、結果どういう学生の質になっているかってのが統計的に分かると嬉しいです。

あと、うちの一番の魅力が、集め方→面談→（営業マンとメンターが両面行ってる）って流れだと思うので、①集客方法とそのメリット、②面談の仕方と企業側のメリット、③相互理解で質向上、みたいな図とフローがあったら良いと思います。
①アナログ
質の担保
紹介を使わない学生層へアプローチ（そもそも紹介事業モデルに集まる学生はレベル低い）
②面談
意思決定のサポート
本質的な人間性の把握
視野、可能性の拡大
企業理解の擦込み
③相互理解
擦り合わせ
質の向上

**Comment by hirokiyamada-reno** [comment]
@kikukawa-reno 

### 学生の質

> うちのシステム上で一応管理している能力値や特性のデータは記載しておくといいと思います。
ユニークっていう部分と、マッチング率が高いって部分の裏付けの目に見える数値的データの根拠があると信頼性あがるかと思います。
そういった意味で、どんな学生がいるかっていうのを、定性的な言葉や文章で伝えるより、定量的に伝えた方がいいかと思います。

それはつまり、属性やジョブ・就活力を載せたほうがいいってこと？載せるのならば、どこまで載せるべきだと思う？就活力は説明を要すから、一度理解してもらえたら楽だけど、そこまでのコストが高い。
### 図とフローについて

HOWの部分をどこまで資料に盛り込むべきなのかは、割と疑問なんだよねー。本当に文字で伝わるもんなのか。なぜ、口頭でなくて、資料に必要なのかの理由というのは何？説明のしやすさが高まるから？

### 実績

大業界に分類しての数字だと、
* 一つ一つが小さい数字になる
* 情報量が多すぎて一ページ埋まる

んだけど、業界ごとに分けるメリットってそこまで大きい？そこまでじゃなければ、全体の数字として出すけど。

**Comment by kikukawa-reno** [comment]
学生の質
・属性、ジョブ、能力値（指標のランクの説明まで）
・第一志望業界、第一志望職種
・企業規模

図とフロー
・説明のしやすさ（新人のため）
・口頭だけで図をイメージさせるのが難しく、直感的にメリットを瞬時に理解してもらうため
・資料だけで受注するため

実績
・業界ごとに分けると、RENOの紹介の強さが分かりやすく、何人くらい紹介されるのかのイメージをしやすい
・実績が無い業界に対して、逆に志望学生がいるのであれば、企業からしたら紹介の可能性がぐんと上がるため、マイナスイメージは無い
・実績がなく、志望学生がいなければ、業界で出すメリットは無い

このように考えました！

**Comment by hirokiyamada-reno** [comment]
学生の質に関しては細かいデータは資料末尾に母集団データとして載せておきます。

図とフローはなんとか、伝えたいことが伝わるようにやってみます。

業界ごとに分けると、実績がないところに紹介できる根拠がなくなるので、全体のみを出します。

こちらで論点としては、終わったかと思うので、closeします。
